export const cat = [
  { id: "sustenance", name: "sustenance" },
  { id: "bar", name: "bar" },
  { id: "biergarten", name: "biergarten" },
  { id: "cafe", name: "cafe" },
  { id: "fast_food", name: "fast food" },
  { id: "food_court", name: "food court" },
  { id: "ice_cream", name: "ice cream" },
  { id: "pub", name: "pub" },
  { id: "restaurant", name: "restaurant" },
  { id: "education", name: "education" },
  { id: "college", name: "college" },
  { id: "driving_school", name: "driving school" },
  { id: "kindergarten", name: "kindergarten" },
  { id: "language_school", name: "language school" },
  { id: "library", name: "library" },
  { id: "toy_library", name: "toy library" },
  { id: "music_school", name: "music school" },
  { id: "school", name: "school" },
  { id: "university", name: "university" },
  { id: "transportation", name: "transportation" },
  { id: "bicycle_parking", name: "bicycle parking" },
  { id: "bicycle_repair_station", name: "bicycle repair station" },
  { id: "bicycle_rental", name: "bicycle rental" },
  { id: "boat_rental", name: "boat rental" },
  { id: "boat_sharing", name: "boat sharing" },
  { id: "bus_station", name: "bus station" },
  { id: "car_pooling", name: "car pooling" },
  { id: "car_rental", name: "car rental" },
  { id: "car_sharing", name: "car sharing" },
  { id: "car_wash", name: "car wash" },
  { id: "compressed_air", name: "compressed air" },
  { id: "charging_station", name: "charging station" },
  { id: "driver_training", name: "driver training" },
  { id: "ferry_terminal", name: "ferry terminal" },
  { id: "fuel", name: "fuel" },
  { id: "grit_bin", name: "grit bin" },
  { id: "motorcycle_parking", name: "motorcycle parking" },
  { id: "parking", name: "parking" },
  { id: "parking_entrance", name: "parking entrance" },
  { id: "parking_space", name: "parking space" },
  { id: "taxi", name: "taxi" },
  { id: "financial", name: "financial" },
  { id: "atm", name: "atm" },
  { id: "bank", name: "bank" },
  { id: "bureau_de_change", name: "bureau de change" },
  { id: "healthcare", name: "healthcare" },
  { id: "baby_hatch", name: "baby hatch" },
  { id: "clinic", name: "clinic" },
  { id: "dentist", name: "dentist" },
  { id: "doctors", name: "doctors" },
  { id: "hospital", name: "hospital" },
  { id: "nursing_home", name: "nursing home" },
  { id: "pharmacy", name: "pharmacy" },
  { id: "social_facility", name: "social facility" },
  { id: "veterinary", name: "veterinary" },
  { id: "entertainment", name: "entertainment" },
  { id: "arts_centre", name: "arts centre" },
  { id: "brothel", name: "brothel" },
  { id: "casino", name: "casino" },
  { id: "cinema", name: "cinema" },
  { id: "community_centre", name: "community centre" },
  { id: "conference_centre", name: "conference centre" },
  { id: "events_venue", name: "events venue" },
  { id: "fountain", name: "fountain" },
  { id: "gambling", name: "gambling" },
  { id: "love_hotel", name: "love hotel" },
  { id: "nightclub", name: "nightclub" },
  { id: "planetarium", name: "planetarium" },
  { id: "public_bookcase", name: "public bookcase" },
  { id: "social_centre", name: "social centre" },
  { id: "stripclub", name: "stripclub" },
  { id: "studio", name: "studio" },
  { id: "theatre", name: "theatre" },
  { id: "public_service", name: "public service" },
  { id: "courthouse", name: "courthouse" },
  { id: "fire_station", name: "fire station" },
  { id: "police", name: "police" },
  { id: "post_box", name: "post box" },
  { id: "post_office", name: "post office" },
  { id: "prison", name: "prison" },
  { id: "townhall", name: "townhall" },
  { id: "facilities", name: "facilities" },
  { id: "bbq", name: "bbq" },
  { id: "bench", name: "bench" },
  { id: "dog_toilet", name: "dog toilet" },
  { id: "dressing_room", name: "dressing room" },
  { id: "drinking_water", name: "drinking water" },
  { id: "give_box", name: "give box" },
  { id: "mail_room", name: "mail room" },
  { id: "parcel_locker", name: "parcel locker" },
  { id: "shelter", name: "shelter" },
  { id: "shower", name: "shower" },
  { id: "telephone", name: "telephone" },
  { id: "toilets", name: "toilets" },
  { id: "water_point", name: "water point" },
  { id: "watering_place", name: "watering place" },
  { id: "waste_management", name: "waste management" },
  { id: "sanitary_dump_station", name: "sanitary dump station" },
  { id: "recycling", name: "recycling" },
  { id: "waste_basket", name: "waste basket" },
  { id: "waste_disposal", name: "waste disposal" },
  { id: "waste_transfer_station", name: "waste transfer station" },
  { id: "others", name: "others" },
  { id: "animal_boarding", name: "animal boarding" },
  { id: "animal_shelter", name: "animal shelter" },
  { id: "baking_oven", name: "baking oven" },
  { id: "clock", name: "clock" },
  { id: "crematorium", name: "crematorium" },
  { id: "dive_centre", name: "dive centre" },
  { id: "funeral_hall", name: "funeral hall" },
  { id: "grave_yard", name: "grave yard" },
  { id: "hunting_stand", name: "hunting stand" },
  { id: "internet_cafe", name: "internet cafe" },
  { id: "kitchen", name: "kitchen" },
  { id: "kneipp_water_cure", name: "kneipp water cure" },
  { id: "marketplace", name: "marketplace" },
  { id: "monastery", name: "monastery" },
  { id: "photo_booth", name: "photo booth" },
  { id: "place_of_mourning", name: "place of mourning" },
  { id: "place_of_worship", name: "place of worship" },
  { id: "public_bath", name: "public bath" },
  { id: "refugee_site", name: "refugee site" },
  { id: "vending_machine", name: "vending machine" }
];