export const zone = [
  { "name": "el Raval" },
  { "name": "el Barri Gòtic" },
  { "name": "la Barceloneta" },
  { "name": "Sant Pere, Santa Caterina i la Ribera" },
  { "name": "el Fort Pienc" },
  { "name": "la Sagrada Família" },
  { "name": "la Dreta de l'Eixample" },
  { "name": "l'Antiga Esquerra de l'Eixample" },
  { "name": "la Nova Esquerra de l'Eixample" },
  { "name": "Sant Antoni" },
  { "name": "el Poble Sec" },
  { "name": "la Marina del Prat Vermell" },
  { "name": "la Marina de Port" },
  { "name": "la Font de la Guatlla" },
  { "name": "Hostafrancs" },
  { "name": "la Bordeta" },
  { "name": "Sants - Badal" },
  { "name": "Sants" },
  { "name": "les Corts" },
  { "name": "la Maternitat i Sant Ramon" },
  { "name": "Pedralbes" },
  { "name": "Vallvidrera, el Tibidabo i les Planes" },
  { "name": "Sarrià" },
  { "name": "les Tres Torres" },
  { "name": "Sant Gervasi - la Bonanova" },
  { "name": "Sant Gervasi - Galvany" },
  { "name": "el Putxet i el Farró" },
  { "name": "Vallcarca i els Penitents" },
  { "name": "el Coll" },
  { "name": "la Salut" },
  { "name": "la Vila de Gràcia" },
  { "name": "el Camp d'en Grassot i Gràcia Nova" },
  { "name": "el Baix Guinardó" },
  { "name": "Can Baró" },
  { "name": "el Guinardó" },
  { "name": "la Font d'en Fargues" },
  { "name": "el Carmel" },
  { "name": "la Teixonera" },
  { "name": "Sant Genís dels Agudells" },
  { "name": "Montbau" },
  { "name": "la Vall d'Hebron" },
  { "name": "Horta" },
  { "name": "Vilapicina i la Torre Llobeta" },
  { "name": "Porta" },
  { "name": "el Turó de la Peira" },
  { "name": "Can Peguera" },
  { "name": "la Guineueta" },
  { "name": "Canyelles" },
  { "name": "les Roquetes" },
  { "name": "Verdun" },
  { "name": "la Prosperitat" },
  { "name": "la Trinitat Nova" },
  { "name": "Torre Baró" },
  { "name": "Ciutat Meridiana" },
  { "name": "Vallbona" },
  { "name": "la Trinitat Vella" },
  { "name": "Baró de Viver" },
  { "name": "el Bon Pastor" },
  { "name": "Sant Andreu de Palomar" },
  { "name": "la Sagrera" },
  { "name": "el Congrés i els Indians" },
  { "name": "Navas" },
  { "name": "el Camp de l'Arpa del Clot" },
  { "name": "el Clot" },
  { "name": "el Parc i la Llacuna del Poblenou" },
  { "name": "la Vila Olímpica del Poblenou" },
  { "name": "el Poblenou" },
  { "name": "Diagonal Mar i el Front Marítim del Poblenou" },
  { "name": "el Besòs i el Maresme" },
  { "name": "Provençals del Poblenou" },
  { "name": "Sant Martí de Provençals" },
  { "name": "la Verneda i la Pau" }
];